Digishop/Models/HomeViewModel.cs
using WebshopLogic;

namespace Digishop.Models
{
    public class HomeViewModel
    {
        // Viewmodel??
         public List<Category> categories = new List<Category>();
         public List<Product> products = new List<Product>();
        public bool signedIn { get; set; }  
        public bool? showOrderPlacedBox { get; set; }
        public bool admin { get; set; }
    }
}

Digishop/Controllers/CartController.cs
using Digishop.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebshopDAL;
using WebshopLogic;

using System;
using System.Collections.Generic;
using System.Net;
using System.Text;
using System.Web;
using System.Text.RegularExpressions;

namespace Digishop.Controllers
{
    public class CartController : Controller
    {
        OrderContainer orderContainer = new OrderContainer(new OrderDAL());
        ProductContainer productContainer = new ProductContainer(new ProductDAL());
        CartViewModel cvm = new CartViewModel();

        public IActionResult Index()
        {
            string CartID = "";

            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("CartID")))
                CartID = HttpContext.Session.GetString("CartID");

            cvm.cartProducts = orderContainer.GetCartProducts(CartID);

            return View(cvm);
        }

        public IActionResult AddProductToCart(int productId)
        {
            //Add product to cart
            Product product =  productContainer.GetProductID(productId);

            if (String.IsNullOrEmpty(HttpContext.Session.GetString("CartID")))
            {
                HttpContext.Session.SetString("CartID", Guid.NewGuid().ToString()); 
            }

            orderContainer.AddToCart(HttpContext.Session.GetString("CartID"), productId, 1, product.ProductPrice);
            
            return Redirect(Request.Headers["Referer"].ToString());
        }

        public IActionResult RemoveProductFromCart(int productId)
        {
            orderContainer.DeleteItemFromCart(HttpContext.Session.GetString("CartID"), productId);

            return Redirect(Request.Headers["Referer"].ToString());
        }

        public IActionResult AddProductAmountToCart(int productId)
        {
            orderContainer.AddProductAmountToCart(HttpContext.Session.GetString("CartID"), productId);

            return Redirect(Request.Headers["Referer"].ToString());
        }


        [HttpPost]
        public IActionResult Order(CartViewModel cvm)
        {
            UserContainer userContainer = new UserContainer(new UserDAL());

            if (String.IsNullOrEmpty(Convert.ToString(HttpContext.Session.GetInt32("UserID"))))
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                int UserID = (int)HttpContext.Session.GetInt32("UserID").Value;

                User user = new User();
                user.UserID = UserID;
                user.PhoneNumber = cvm.PhoneNumber;
                user.Address = cvm.Address;
                user.HouseNumber = cvm.HouseNumber;
                user.PostalCode = cvm.PostalCode;
                user.City = cvm.City;

                userContainer.UpdateUserAddress(user);

                if (orderContainer.PlaceOrder(UserID, HttpContext.Session.GetString("CartID")))
                {
                    HttpContext.Session.SetString("CartID", Guid.NewGuid().ToString());
                    return RedirectToAction("Index", "Home", new { OrderPlaced = true });
                }
                else
                {
                    return RedirectToAction("Index", "Home", new { OrderPlaced = false });
                }

            }
        }
    }
}

Digishop/Controllers/CategoryController.cs
using Digishop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using WebshopDAL;
using WebshopLogic;

namespace Digishop.Controllers
{
    public class CategoryController : Controller
    {
        CategoryContainer categoryContainer = new CategoryContainer(new CategoryDAL());
        ProductContainer productContainer = new ProductContainer(new ProductDAL()); 
        CategoryViewModel cvm = new CategoryViewModel();

        public IActionResult Index(int categoryID)
        {
            cvm.products = productContainer.GetAllProductsByCategoryID(categoryID);
            cvm.CategoryName = categoryContainer.GetCategoryNameByCategoryID(categoryID);
            cvm.categories = categoryContainer.GetAllCategories();
            //  cvm.products = ProductContainer

            if (HttpContext.Session.GetInt32("UserID") != null)
            {
                //gebruiker is ingelogd
                cvm.signedIn = true;

                //kijk of de user madmin is
                if (HttpContext.Session.GetInt32("IsAdmin") == 1)
                {
                    cvm.admin = true;
                }
                else
                {
                    cvm.admin = false;
                }
            }
            else
            {
                cvm.signedIn = false;
            }

            return View(cvm);
        }

        [HttpPost]
        public IActionResult CreateCategory(CategoryViewModel cvm)
        {
            if (!categoryContainer.CategoryExist(cvm.CategoryName))
            {
                var createcategory = categoryContainer.CreateCategory(cvm.CategoryName);
            }
            else
            {
                ViewBag.Message = "Deze categorienaam bestaat al, maak een andere categorienaam aan";

            }
            return View(new CategoryViewModel()
            {
                categories = categoryContainer.GetAllCategories()
            });

        }
        [HttpGet]
        public IActionResult CreateCategory()
        {
            return View(new CategoryViewModel(null)
            {
                categories = categoryContainer.GetAllCategories()
            });
        }
    }
}

Digishop/Controllers/HomeController.cs
using Digishop.Models;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebshopDAL;
using WebshopLogic;

namespace Digishop.Controllers
{
    public class HomeController : Controller
    {
        //Product product = new Product();
        ProductContainer productContainer = new ProductContainer(new ProductDAL());
        CategoryContainer categoryContainer = new CategoryContainer(new CategoryDAL()); 
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            
            HomeViewModel hvm = new HomeViewModel();
            
            hvm.products = productContainer.GetTop8product();
            hvm.categories = categoryContainer.GetAllCategories();

            if (HttpContext.Request.QueryString.HasValue && HttpContext.Request.Query["OrderPlaced"].ToString() == "True")
            {
                hvm.showOrderPlacedBox = true;                
            }
            else if(HttpContext.Request.QueryString.HasValue && HttpContext.Request.Query["OrderPlaced"].ToString() == "False")
            {
                hvm.showOrderPlacedBox = false;
            }
            else
            {
                hvm.showOrderPlacedBox = null;
            }

            if(HttpContext.Session.GetInt32("UserID") != null)
            {
                //gebruiker is ingelogd
                hvm.signedIn = true;

                //kijk of de user madmin is
                if (HttpContext.Session.GetInt32("IsAdmin") == 1)
                {
                    hvm.admin = true;
                }
                else
                {
                    hvm.admin = false;
                }
            }
            else
            {
                hvm.signedIn = false;
            }
            return View(hvm);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Digishop/Controllers/ProductController.cs
using Digishop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.Runtime.CompilerServices;
using WebshopDAL;
using WebshopInterface;
using WebshopLogic;
using WebshopLogic.Helper;

namespace Digishop.Controllers
{
    public class ProductController : Controller
    {
        Product product = new Product();
        ProductContainer productContainer = new ProductContainer(new ProductDAL());
        CategoryContainer categoryContainer = new CategoryContainer(new CategoryDAL()); 
        ProductViewModel productViewModel = new ProductViewModel();
        ReviewContainer reviewContainer = new ReviewContainer(new ReviewDAL());
        Review review = new Review();   

        public IActionResult Index(int id)
        {
            Product product = productContainer.GetProductID(id);
            ProductViewModel pvm = new ProductViewModel(product);

            return View(pvm);
        }

        [HttpPost]
        public IActionResult Index(ProductViewModel pvm)
        {
            if (reviewContainer.CheckIfUserHasProductReviewed(pvm.ProductID, Convert.ToInt32(HttpContext.Session.GetInt32("UserID"))))
            {
                return View(pvm);
            }
            review.Created = DateTime.Now;
            review.Title = pvm.reviewTitle;
            review.Text = pvm.reviewString;
            review.ProductID = pvm.ProductID;
            review.UserID = Convert.ToInt32(HttpContext.Session.GetInt32("UserID"));
            reviewContainer.CreateReview(review);
            return View();
        }

        [HttpPost]
        public IActionResult CreateProduct(ProductViewModel pvm)
        {
            if (!productContainer.ExistProduct(pvm.ProductName))
            {
                product.ProductName = pvm.ProductName;
                product.ProductPrice = pvm.ProductPrice;
                product.ProductDescription = pvm.ProductDescription;
                product.ProductImage = pvm.ProductImage;
                product.CategoryID = pvm.CategoryID;
                productContainer.CreateProduct(product);
            }
            else
            {
                TempData["message"] = "Deze productnaam heb je al";
            }
            return RedirectToAction("CreateProduct"); 

        }
        [HttpGet]
        public IActionResult CreateProduct()
        {
            ProductViewModel pvm = new ProductViewModel(categoryContainer.GetAllCategories());
            pvm.products = productContainer.GetAllProducts();
            //pvm.Delete = productContainer.ArchiveProduct(product.ProductID);

            
            return View(pvm);
        }
        [HttpPost]
        public IActionResult ArchiveProduct(ProductViewModel pvm)
        {
            productContainer.ArchiveProduct(pvm.ProductID);
            return RedirectToAction(nameof(CreateProduct));
        }

        [HttpGet]
        public IActionResult ArchiveProduct(int id)
        {
            product = productContainer.GetProductID(id);
            productViewModel = new ProductViewModel(product);
            return View (productViewModel);
        }
        [HttpPost]
        public IActionResult UnarchiveProduct(ProductViewModel pvm)
        {
            productContainer.UnarchiveProduct(pvm.ProductID);
            return RedirectToAction(nameof(CreateProduct));
        }
        [HttpGet]
        public IActionResult UnarchiveProduct(int id)
        {
            product = productContainer.GetProductID(id);
            productViewModel = new ProductViewModel(product);
            return View(productViewModel);
        }
    }
}

Digishop/Views/Home/Index.cshtml
@using WebshopLogic
@model HomeViewModel

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="UFT-8" />
    <meta http-equiv="X-UA-Compatible" content=" IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Digishop</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />

</head>
<body>

    <section id="header">
        <a asp-controller="Home" asp-action="Index"><img src="images/LogoV2.png" class="logo" alt="" /></a>

        <div>
            <ul id="navbar">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li>
                    <a href="">Alle Categorieën &dtrif;</a>
                    <ul class="dropdown">
                        @foreach (Category category in Model.categories)
                        {
                            <li><a asp-controller="Category" asp-action="Index" asp-route-categoryID="@category.CategoryID">@category.CategoryName</a></li>
                        }
                    </ul>
                </li>
                @if (!Model.signedIn)
                {
                    <li><a asp-controller="User" asp-action="Login">Inloggen</a></li>
                    <li><a asp-controller="User" asp-action="CreateUser">Registreren</a></li>
                }

                @if (Model.signedIn && Model.admin)
                {
                    <li><a asp-controller="Category" asp-action="CreateCategory">Voeg Categorie toe</a></li>
                    <li><a asp-controller="Product" asp-action="CreateProduct">Voeg product toe</a></li>
                }

                @if (Model.signedIn)
                {
                    <li><a asp-controller="User" asp-action="Logout">Uitloggen</a></li>
                }

                <li>
                    <a asp-controller="Cart" asp-action="Index">
                        <i class="far fa-shopping-bag"></i>
                    </a>
                </li>


            </ul>
        </div>
    </section>

    @if (!Model.showOrderPlacedBox.HasValue)
    {
    }
    else if(Model.showOrderPlacedBox.Value == false)
    {
        <h3 style="color: red;">Je bestelling is niet gelukt</h3>
    }
    else if (Model.showOrderPlacedBox.Value == true)
    {
        <h3 style="color: green;">Je bestelling is succesvol geplaatst.</h3>
    }

    <section id="hero">
        <h4>Aanbieding</h4>
        <h2>Super lage prijzen</h2>
        <h1>Op bijna alle artikelen</h1>
        <p>Bespaar meer dan 70% op je volgende aankoop</p>
        <button>Bestel Nu</button>
    </section>

    <section id="feature" class="section-p1">
        <h2>De 6 zékerheden van Digishop</h2>
        <div class="box-container">
            <div class="fe-box">
                <img src="images/features/f1.png" alt="" />
                <h6>Gratis verzending</h6>
            </div>
            <div class="fe-box">
                <img src="images/features/f2.png" alt="" />
                <h6>Bestel online</h6>
            </div>
            <div class="fe-box">
                <img src="images/features/f3.png" alt="" />
                <h6>Euro's goedkoper</h6>
            </div>
            <div class="fe-box">
                <img src="images/features/f4.png" alt="" />
                <h6>Aanbiedingen</h6>
            </div>
            <div class="fe-box">
                <img src="images/features/f5.png" alt="" />
                <h6>Service met een glimlach</h6>
            </div>
            <div class="fe-box">
                <img src="images/features/f6.png" alt="" />
                <h6>24/7 Service</h6>
            </div>
        </div>

    </section>

    <section id="product1" class="section-p1">
        <h2>Uitgelichte Producten</h2>
        <p>Nieuw</p>
        <div class="pro-container">
            @foreach (Product pvm in Model.products)
            {
                <a asp-controller="Product" asp-action="Index" asp-route-id="@pvm.ProductID">
                    <div class="pro">
                        <img src="@pvm.ProductImage" alt="" />
                        <div class="des">
                            <h5>@pvm.ProductName</h5>
                            <div class="star">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h4>€@pvm.ProductPrice</h4>
                        </div>
                        <a asp-controller="Cart" asp-action="AddProductToCart" asp-route-productId="@pvm.ProductID"><i class="fal fa-shopping-cart cart"></i></a>
                    </div>
                </a>

            }
        </div>
    </section>

    <section id="banner" class="section-m1">
        <h4>Tijdelijke Aanbiedingen</h4>
        <h2>Tot wel <span>70% korting</span> op alle muizen en toetsenborden</h2>
        <button class="normal">Ontdek meer</button>
    </section>

    <footer class="section-p1">
        <div class="col">
            <img class="logo" src="images/LogoV2.png" alt="" />
            <h4>Contact</h4>
            <p><strong>Adres:</strong> Professor Goossenlaan 1</p>
            <p><strong>Telefoon nummer</strong>(+31) 64234378</p>
            <p><strong>Openingstijden</strong> 10:00 - 18:00, maandag tot en met zaterdag</p>
            <div class="follow">
                <h4>Volg ons ook op</h4>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-pinterest-p"></i>
                    <i class="fab fa-youtube"></i>
                </div>
            </div>
        </div>
        <div class="col">
            <h4>Informatie</h4>
            <a href="#">Over ons</a>
            <a href="#">Verzending</a>
            <a href="#">privacybeleid</a>
            <a href="#">Algemene Voorwaarden</a>
            <a href="#">Contact</a>
        </div>

        <div class="col">
            <h4>Mijn account</h4>
            <a href="#">Inloggen</a>
            <a href="#">Winkelwagen</a>
            <a href="#">Wenslijst</a>
            <a href="#">Volg Mijn Bestelling</a>
            <a href="#">Help</a>
        </div>
        <div class="col install">
            <h4>Veilig betalen</h4>
            <img src="images/pay.png" alt="" />
        </div>
        <div class="copyright">
            <p>© 2022, Tech2 etc - HTML CSS Ecommerce Template</p>
        </div>
    </footer>

    <script src="~/js/site.js"></script>
</body>

</html>